### ISSUE TITLE
Week 2 Step 1

### ISSUE THREAD

**Issue by lazyplatypus** [bitprj/Intro-To-Serverless#110]
---
files: n/a
stepType: checks
scripts: test.parseimage.js
week: 2
step: 1
name: Week 2 Step 1
---
Week 2 Step 1 ⬤◯◯◯◯◯◯ | 🕐 Estimated completion: 5-20 minutes

## Getting Emotional ~ With the Face API

Because of amazing APIs, you don't need to be an expert in machine learning and AI to take advantage of cutting edge technology. In this project, we are going to be building an API and webpage to return you a GIF when you upload a picture of yourself!

### ✅ Task:

**Create a request in Postman to send an image of a person to the Azure Face API to return the subject's emotions**
- [ ] Create a Face [API Endpoint](https://smartbear.com/learn/performance-monitoring/api-endpoints/#:~:text=For%20APIs%2C%20an%20endpoint%20can,to%20carry%20out%20their%20function.&text=The%20place%20that%20APIs%20send,lives%2C%20is%20called%20an%20endpoint.)
- [ ] Create a POST request in Postman to the Face API to retrieve the emotion attributes
- [ ] Comment the output of your Postman request to move on

### 🚧 Test your Work

<details>
<summary>:white_check_mark: Expected Output </summary>

```json
{
  "result": [
    {
      "faceId": "d25465d6-0c38-4417-8466-cabdd908e756",
      "faceRectangle": {
        "top": 313,
        "left": 210,
        "width": 594,
        "height": 594
      },
      "faceAttributes": {
        "emotion": {
          "anger": 0,
          "contempt": 0,
          "disgust": 0,
          "fear": 0,
          "happiness": 1,
          "neutral": 0,
          "sadness": 0,
          "surprise": 0
        }
      }
    }
  ]
}
```

</details>

### The Face API 

The Face API will accept the image and return information about the face, specifically emotions. Watch this video on Microsoft Cognitive Services for an in-depth explanation: http://www.youtube.com/watch?v=2aA8OEZ1wk8 

<details>
<summary>❓ How do I create and access the Face API?</summary>
</br>

1. Log into your Azure portal
2. Navigate to **Create a Resource**, the **AI + Machine Learning** tab on the left, and finally select **Face** and fill out the necessary information
3. Record and save the API endpoint and [subscription key](https://docs.microsoft.com/en-us/azure/api-management/api-management-subscriptions)
4. Place the API endpoint and subscrition key in the GitHub repository secrets: `API_ENDPOINT` AND `SUBSCRIPTION_KEY`
    * These keys will be used in the Azure function to give access to this API

<br>

</details>
<details>
<summary>❓ Where can I find the Face API keys?</summary>
 </br>

1. Navigate to the home page on the Micrsoft Azure portal (https://portal.azure.com/#home)
<img width="1440" alt="Screen Shot 2021-02-04 at 4 00 33 PM" src="https://user-images.githubusercontent.com/28051494/106971033-edac0000-6702-11eb-8243-1b5c2318f76d.png">

2. Click on the resource you need the keys for
<img width="1438" alt="Screen Shot 2021-02-04 at 4 00 49 PM" src="https://user-images.githubusercontent.com/28051494/106971035-ef75c380-6702-11eb-965b-c3ef7b5a7574.png">

3. On the left menu bar, locate the Resource Management section and click on "Keys and Endpoint"
<img width="1440" alt="Screen Shot 2021-02-04 at 12 26 36 PM" src="https://user-images.githubusercontent.com/28051494/106971042-f43a7780-6702-11eb-9e28-e6b2bc16fa22.png">
<br>
</details>

### Using Postman to Send a Request
Now, we can test if our API is working using Postman. Make sure to pay close attention to the documentation and [the API Reference](https://westus.dev.cognitive.microsoft.com/docs/services/563879b61984550e40cbbe8d/operations/563879b61984550f30395236)

:bulb: **Request URL** is used when a web client makes a request to a server for a resource. Notice that the request url is this:

`https://{endpoint}/face/v1.0/detect\[?returnFaceId]\[&returnFaceLandmarks]\[&returnFaceAttributes]\[&recognitionModel]\[&returnRecognitionModel][&detectionModel]`

:bulb: **Parameters** are typically used in requests to APIs to specify settings or customize what **YOU** want to receive.

<details>
<summary>❓ What are the parameters for the request?</summary>
</br>
Notice the Request URL has the following parameters in [ ]:

* [?returnFaceId]
* [&returnFaceLandmarks]
* [&returnFaceAttributes]
* [&recognitionModel]
* [&returnRecognitionModel]
* [&detectionModel]

All of the bracketed sections represent possible request parameters. Read through **Request Parameters** section carefully. How can we specify that we want to get the emotion data?

In order to specify all of our parameters easily, we're going to create a new `URLSearchParams`  object. Here's the object declared for you. I've also already specified one parameter, `returnFaceId`,  as `true` to provide an example. Add in a new parameter that requests emotion.

</details>
<br>

:bulb: **Request Headers** tell the receiving end of the request what *type* of data is in the body.

<details>
<summary>❓ How do I specify Request Headers?</summary>
</br>

Go back to the Face API documentation [here](https://westus.dev.cognitive.microsoft.com/docs/services/563879b61984550e40cbbe8d/operations/563879b61984550f30395236), and find the **Request headers** section. 

The `Content-Type`  header should be set to`'application/octet-stream'`.  This specifies a binary file.

The `Ocp-Apim-Subscription-Key`  header should be set to one of your two keys from your Face API resource.

</details>
</br>

**Comment by emsesc** [comment]
Maybe you could link *where* you found the request url in the documentation so students know how to search for it next time. @lazyplatypus 

Maybe also tips on how to read documentation? Like quick hints
