### ISSUE TITLE
Week 2 Step 2 - Parse Multipart

### ISSUE THREAD

**Issue by lazyplatypus** [bitprj/Intro-To-Serverless#127]
---
files: n/a
stepType: checks
scripts: test.parseimage.js
week: 2
step: 2
name: Week 2 Step 2
---
Week 2 Step 2 ⬤⬤◯◯◯◯◯ | 🕐 Estimated completion: 5-20 minutes

### ✅ Task:
**Create an Azure function that takes in an image from a HTTP request, parses it with parse-multipart, and returns the base64 code of the image**
- [ ] Create a new Azure Function called `emotionalgifs` with the HTTP Trigger template
- [ ] install npm package `parse-multipart`
- [ ] Place your function URL in a [repository secret](https://docs.github.com/en/actions/reference/encrypted-secrets#creating-encrypted-secrets-for-a-repository) called `EMOTIONAL_FUNCTION`
- [ ] Commit your code to `week2/emotional.js`

### 🚧 Test your Work
Use **Postman**! Paste the *function url* and make a POST request. Remember to attach the file in `Body`! In the output box, you should get the output. Make sure you're using an image with a *real face* on it or else it won't work. Here's an example of an output I get with [this image](https://user-images.githubusercontent.com/69332964/98884689-91687580-245e-11eb-98d7-6461ac79e02a.jpg):

<details>
<summary>:white_check_mark: Expected Output </summary>

```json
{
  "result": {
    "type": "Buffer",
    "data": [
      255,
      216,
      255,
      224,
      0, ..
      217
    ]
  }
}
```

</details>

<details>
<summary>:question: Confused about Postman? </summary>

* Navigate back to the Postman app and change GET to POST
![Untitled_ Nov 11, 2020 6_24 PM](https://user-images.githubusercontent.com/69332964/98876201-c3bca780-244b-11eb-9b94-8d3cecc80115.gif)

* Copy your function's url from the Azure Function App portal like this:
![httptrigger - Microsoft Azure](https://user-images.githubusercontent.com/69332964/98876502-6f65f780-244c-11eb-832b-a25888b980da.gif)

* Use the function url and any image you want to send the POST request. Remember to attach the file in Body!
![Untitled_ Nov 11, 2020 6_40 PM](https://user-images.githubusercontent.com/69332964/98876997-780afd80-244d-11eb-87fc-13822d909f2f.gif)
</details>

## What is multipart request?
A **HTTP multipart request** is a HTTP request that HTTP clients construct to send files and data over to a HTTP Server. 

> 💡 This is commonly used by browsers and HTTP clients to **upload** files to the server.

Because we want to send an image file through an HTTP Request, we need a piece of software to parse the raw data to extract the image file. Here comes the handy NPM package: `parse-multipart`! 

The raw payload formatted as multipart/form-data will looks like this one:

```
------WebKitFormBoundaryDtbT5UpPj83kllfw
Content-Disposition: form-data; name="uploads[]"; filename="somebinary.dat"
Content-Type: application/octet-stream

some binary data...maybe the bits of a image..
------WebKitFormBoundaryDtbT5UpPj83kllfw
Content-Disposition: form-data; name="uploads[]"; filename="sometext.txt"
Content-Type: text/plain

hello how are you
------WebKitFormBoundaryDtbT5UpPj83kllfw--
```

The lines above represents a **raw multipart/form-data payload** sent by some HTTP client via form submission containing two files. We need to extract the all files contained inside it. The multipart format allows you to send more than one file in the same payload, that's why it is called: multipart.

<details>
<summary>How do I use this package?</summary>
</br>

Notice that `multipart.Parse(body, boundary)`  requires two parameters.  I've already gotten the boundary for you – just like the documentation example, our boundary is a string in the format `"----WebKitFormBoundary(random characters here)"`.

In the `multipart.Parse()` call, you need to figure out what the body parameter should be.

> :bulb: **Hint:** It should be the request body. Think about the template HTTP Trigger Azure function. How did we access the body in there?

```js

// here's your boundary:
var boundary = multipart.getBoundary(req.headers['content-type']);
  
// TODO: assign the body variable the correct value
var body = '<WHAT GOES HERE?>'

// parse the body
var parts = multipart.Parse(body, boundary);
```
</details>

## 🖼️ Receiving the image
We will be making a **POST request** to the function with an image, which *will be sent in the body*.

Take a look at the standard `module.exports` function code:

```js
module.exports = async function (context, req) {
    // the code
}
```

This is the function that runs **every time your HTTP trigger gets a request**. As a parameter of this function, the `req` parameter contains all the information the request was sent with. *This contains*:
* Headers
* The body

We will be using the `req` parameter to get the image that was sent through the **body** of the POST request.

```js
let img = req.body
```
<br>
</details>

<br></br>

**Comment by lazyplatypus** [comment]
solution

```javascript
var multipart = require("parse-multipart");
  
module.exports = async function (context, req) {
    context.log('JavaScript HTTP trigger function processed a request.'); 

    var boundary = multipart.getBoundary(req.headers['content-type']);
    // parse the body
    var parts = multipart.Parse(req.body, boundary);
    var finalv = parts[0].data;
    context.res = {
        body: {
            finalv
        }
    };
    context.done(); 
};
```

**Comment by lazyplatypus** [comment]
We need to edit the `How do I use this package?` section

**Comment by emsesc** [comment]
I edited a few things formatting wise, @lazyplatypus how do you suggest we edit that?

> We need to edit the `How do I use this package?` section

**Comment by lazyplatypus** [comment]
it doesn't make sense with the solution lol
