### ISSUE TITLE
Week 2 Step 3 - Node Fetch 

### ISSUE THREAD

**Issue by lazyplatypus** [bitprj/Intro-To-Serverless#128]
---
files: n/a
stepType: checks
scripts: test.parseimage.js
week: 2
step: 3
name: Week 2 Step 3
---
Week 2 Step 3 ⬤◯◯◯◯◯◯ | 🕐 Estimated completion: 5-20 minutes

## Using Node Fetch to Call the Face API
Remember back in step 1 we used Postman to call the API? Well we are going to call the Face API with our Azure Function!

### ✅ Task:
**Create an Azure function that can send a static image to the Face API that returns emotion data**
- [ ] Add Face API Keys into your Function App Secrets
- [ ] Edit your function to make a request to the Face API and send back the emotion data in the body in JSON format
- [ ] Place your function URL in a [repository secret](https://docs.github.com/en/actions/reference/encrypted-secrets#creating-encrypted-secrets-for-a-repository) called `EMOTIONAL_FUNCTION`
- [ ] Commit your code to `week2/emotional.js`

**Comment by lazyplatypus** [comment]
```diff
var multipart = require("parse-multipart");
var fetch = require('node-fetch');
  
module.exports = async function (context, req) {
    context.log('JavaScript HTTP trigger function processed a request.'); 

   var boundary = multipart.getBoundary(req.headers['content-type']);
    var parts = multipart.Parse(req.body, boundary);
    
+    var result = await analyzeImage(parts[0].data);

    context.res = {
        body: {
+            result
        }
    };
    console.log(result)
    context.done(); 
};
 
+async function analyzeImage(byteArray){
    
+   const subscriptionKey = process.env.subscriptionKey
+    const uriBase = process.env.uriBase + '/face/v1.0/detect';

+    let params = new URLSearchParams({
+       'returnFaceId': 'true',
+      'returnFaceAttributes': 'emotion'
+    })

+    let resp= await fetch(uriBase + `?${params.toString()}`, {
+        method: 'POST',
+        body: byteArray,
+        headers: {
+            'Content-Type': "application/octet-stream",
+            "Ocp-Apim-Subscription-Key": subscriptionKey
+        }
+    })

+    let data = await resp.json();
    
+   return data; 
+}
```

**Comment by lazyplatypus** [comment]
#### 🖼️ Receiving the image

We will be making a **POST request** to the function with an image, which *will be sent in the body*.

<details>
<summary>❓ How can I receive an image from the body of the POST request?</summary>
 </br>

Take a look at the standard `module.exports` function code:

```js
module.exports = async function (context, req) {
    // the code
}
```

This is the function that runs **every time your HTTP trigger gets a request**. As a parameter of this function, the `req` parameter contains all the information the request was sent with. *This contains*:
* Headers
* The body

We will be using the `req` parameter to get the image that was sent through the **body** of the POST request.

```js
let img = req.body
```
<br>
</details>

After you receive the image data from the body, pass it on to the async function!
<br></br>




#### 🕐 Asynchronous Functions
Create a new function `analyzeImage(img)` outside of  `module.exports`  that will handle analyzing the image. Keep in mind this function is **async** because we will be using the **await** keyword with the API call.

Javascript is what we call a "synchronous" language, meaning operations in Javascript block other operations from executing until they are complete, creating a sense of single directional flow. **This means that only one operation can happen at a time.** However, in order to maximize efficiency (save time and resources), Javascript allows the use of asynchronous functions.

> Get your Face API keys ready! We need to let our Face API know that we are authenticated to access this resource.
<details>
<summary> :exclamation: How should I define the keys to authenticate my request?</summary>
</br>
This function takes in one parameter, `img`, that contains the image we're trying to analyze.  Inside, we have two variables involved in the call: `subscriptionKey`  and `uriBase`.  

The `process.env` object allows you to access super-secret values in your backend. This prevents hackers from getting your keys and doing bad stuff (like exploiting your resources).

```js
async function analyzeImage(img){
    const subscriptionKey = process.env.SUBSCRIPTIONKEY;
    const uriBase = process.env.ENDPOINT + '/face/v1.0/detect';
}
```

**[Where](https://docs.microsoft.com/en-us/azure/azure-functions/functions-how-to-use-azure-function-app-settings?tabs=portal) do you add the values?**

Head to your Function App and click on `Configuration.`
![image](https://user-images.githubusercontent.com/69332964/117517193-345eff80-af69-11eb-9284-5e5c2380f382.png)


Then, let's add the secrets by clicking `New application setting`.
![image](https://user-images.githubusercontent.com/69332964/117517158-18f3f480-af69-11eb-8efa-579063ad7d00.png)

Let's hope you have your subscription keys and endpoint handy. Add them in as `SUBSCRIPTIONKEY` and `ENDPOINT`.

> Congrats! Your keys are now safe.
</details>


<details>
<summary>❗️ Specify the parameters for your request!</summary>
</br>

In order to specify all of our parameters easily, we're going to create a new `URLSearchParams`  object. Here's the object declared for you. I've also already specified one parameter, `returnFaceId`,  as `true` to provide an example. Add in a new parameter that requests emotion.

```js
let params = new URLSearchParams({
	'returnFaceId': 'true',
	'<PARAMETER NAME>': '<PARAMETER VALUE>'     //FILL IN THIS LINE
})
```

</details>
<br>

#### 🐕 Using `Node-Fetch`

In order to make POST request, we'll be using the `node-fetch` package. [What is the node-fetch package?](https://www.npmjs.com/package/node-fetch) Install it!

We're calling the `fetch` function - notice the **await** keyword, which we need because `fetch` returns a **Promise**, which is a proxy for a value that isn't currently known. You can read about Javascript promises [here](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise). 

<br>

<details>
<summary>❓ What is an async function?</summary>
</br>

Simply put, async functions allow other operations to continue running as they are being executed. Refer to [this site](https://dev.to/hardy613/asynchronous-vs-synchronous-programming-23ed) for more information.

Promises are sychnronous objects, similar to their real life meaning, return a value at some point in the future, or a reason for why that value could not be returned - they represent the result of an async function that may or may not be resolved.

> [Is JavaScript Synchronous or Asynchronous? What the Heck is a Promise?](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise)
> [Master the JavaScript Interview: What is a Promise?](https://medium.com/better-programming/is-javascript-synchronous-or-asynchronous-what-the-hell-is-a-promise-7aa9dd8f3bfb)
</br>
</details>
<br>
```js
//install the node-fetch pacakge
var fetch = '<CODE HERE>'
```
When you've finished installing, read through the [**API** section](https://www.npmjs.com/package/node-fetch#api) of the documentation. We're going to make a call using the `fetch(url, {options})` function.

> API Documentation can be tricky sometimes...Here's something to [help](https://learn.parabola.io/docs/reading-api-docs)
</details>

<details>
<summary>❓ What is the URL?</summary>
</br>

Notice that the URL is just the uriBase with the params we specified earlier appended on.

Fill in the `method`  and `body`.

```js
async function analyzeImage(img){
    
    const subscriptionKey = '<YOUR SUBSCRIPTION KEY>';
    const uriBase = '<YOUR ENDPOINT>' + '/face/v1.0/detect';
    let params = new URLSearchParams({
        'returnFaceId': 'true',
        'returnFaceAttributes': 'emotion'
    })
    //COMPLETE THE CODE
    let resp = await fetch(uriBase + '?' + params.toString(), {
        method: '<METHOD>',  //WHAT TYPE OF REQUEST?
        body: '<BODY>',  //WHAT ARE WE SENDING TO THE API?
        headers: {
            '<HEADER NAME>': '<HEADER VALUE>'  //do this in the next section
        }
    })
    let data = await resp.json();
    
    return data; 
}
```
</details>

> :bulb: **Request Headers** tell the receiving end of the request what *type* of data is in the body.
<details>
<summary>❓ How do I specify Request Headers?</summary>
</br>

Go back to the Face API documentation [here](https://westus.dev.cognitive.microsoft.com/docs/services/563879b61984550e40cbbe8d/operations/563879b61984550f30395236), and find the **Request headers** section. 

There are two headers that you need. I've provided the format below. Enter in the two header names and their two corresponding values. 

FYI: The `Content-Type`  header should be set to`'application/octet-stream'`.  This specifies a binary file.

```js
    //COMPLETE THE CODE
    let resp = await fetch(uriBase + '?' + params.toString(), {
        method: '<METHOD>',  //WHAT TYPE OF REQUEST?
        body: '<BODY>',  //WHAT ARE WE SENDING TO THE API?
      
      	//ADD YOUR TWO HEADERS HERE
        headers: {
            '<HEADER NAME>': '<HEADER VALUE>'
        }
    })
```

</details>
</br>

#### ⏬ Receiving Data
<details>
<summary>❓ How do I actually analyze the image?</summary>
</br>

Call the `analyzeImage` function in `module.exports`. Add the code below into `module.exports`.

Remember that `parts` represents the parsed multipart form data. It is an `array` of parts, each one described by a filename, a type and a data. Since we only sent one file, it is stored in index 0, and we want the `data`  property to access the binary file– hence `parts[0].data`. Then in the HTTP response of our Azure function, we store the result of the API call.

```js
//module.exports function
//analyze the image
var result = await analyzeImage(parts[0].data);
context.res = {
	body: {
		result
	}
};
console.log(result)
context.done(); 
```

</details>
