### ISSUE TITLE
Week 2 Step 4 - Which emotion are you?

### ISSUE THREAD

**Issue by lazyplatypus** [bitprj/Intro-To-Serverless#129]
### ✅ Task:
**Add on to your Azure function so that it determines and returns the face's prominent emotion**

- [ ]  Run `git pull` 
- [ ]  Make sure you are in the `week2` branch 
- [ ]  Modify your serverless function from the previous step to determine the dominant emotion
- [ ] Commit your code to `week2/emotional.js`

## Determining the dominant emotion
Previously, we received a **JSON object of emotion data** as the result from our API. Now, to take it a step further, we need to identify which emotion **has the highest value**.

<details>
<summary>How can I find the dominant emotion?</summary>
</br>

Take a look at the JSON object with emotion data:
> :bulb: Tip: You can see this if you use `context.log(result)`
```json
      {
        "faceId": "d25465d6-0c38-4417-8466-cabdd908e756",
        "faceRectangle": {
          "top": 313,
          "left": 210,
          "width": 594,
          "height": 594
        },
        "faceAttributes": {
          "emotion": {
            "anger": 0,
            "contempt": 0,
            "disgust": 0,
            "fear": 0,
            "happiness": 1,
            "neutral": 0,
            "sadness": 0,
            "surprise": 0
          }
        }
      }
    ]
```
First, let's define the emotions we're going to be analyzing. In this case, `result` is the JSON object/array.
```js
let emotions = result[0].faceAttributes.emotion
```

This narrows down the array to:
```json
{
    "anger": 0,
    "contempt": 0,
    "disgust": 0,
    "fear": 0,
    "happiness": 1,
    "neutral": 0,
    "sadness": 0,
    "surprise": 0
}
```

Now, to find the max value, we an isolate the key values (ex: 0, 0, 1) into another array.
```js
let objects = Object.values(emotions)
```

If you `console.log` the `objects` array, you would get something like: `[0, 0, 0, 0, 1, 0, 0, 0]`. Now, [**write a line of code that identifies the greatest value in this array**](https://medium.com/@vladbezden/how-to-get-min-or-max-of-an-array-in-javascript-1c264ec6e1aa). Name the value `maxemotion`!

Finally, let's search for the max value (which is 1) in the `emotions` JSON object.
```js
const key = Object.keys(emotions).find(key => emotions[key] === maxemotion)
// Object.keys lists out "fear, happiness, neutral, etc." and the .find() method matches the value 1 (maxemotion) with a key.
```

The variable `key` should now contain the dominant emotion.
</details>

**Comment by emsesc** [comment]
**Code solution**:

```js
    let emotions = result[0].faceAttributes.emotion
    let objects = Object.values(emotions)
    const key = Object.keys(emotions).find(key => emotions[key] === Math.max(...objects))

    let final_poem = poems[key]
```
