### ISSUE TITLE
Create a uniform Format for Issues

### ISSUE THREAD

**Issue by lazyplatypus** [bitprj/Intro-To-Serverless#84]
Proposed Format below

**Week 1 Step 1** ⬤◯◯◯◯◯◯◯  | 🕐 **Estimated completion:** 5mins-20 mins

### ✅  Task:

- [ ]  Create a new branch named `test`
- [ ]  Add a paragraph introducing yourself under the `About Me` section in the `blog.md`
- [ ]  Commit the change to `test`
- [ ]  Make a pull request to your main branch
- [ ]  Merge the pull request

## ❓ If you are confused

<details>
<summary><b>:question: What is Github?</b></summary>
</br>

GitHub is a platform that is widely used in the tech industry, that enables code hosting and makes collaboration for coding a seamless process. You can use GitHub to manage your files, changes in your project, version control (the ability to revert back to previous versions of your code as well as versions developed by other programmers), and more.

[Get started with GitHub](https://guides.github.com/activities/hello-world/)
<br></br>
Check out <a href="https://guides.github.com/introduction/flow/">"The Github Flow"</a> for more information on issues, pull requests, committing, and branches!
<br><br/>
</details>

<details>
  <summary>:question: Help! How does Github work?</summary>
<details>
<summary>:question: What is a Repo? </summary>
  </br>
  
Repositories (or repos) are essentially **folders where you can store files of code.** The repo of our camp was duplicated into your account when you clicked "Create Template" so that you can commit changes and complete each lesson.

For our camp, each week is placed inside an issue. Only when you complete the week (committing the necessary code and commenting), will the issue close and you can move on to the next issue. Don’t worry – committing changes is easier than it sounds.
<br><br/>
</details>

<details>
<summary>:exclamation: How can I use GitHub Desktop to commit my code?</summary>
  </br>
  
1. Download GitHub desktop. This is one way you can commit changes to the cabin repo to complete each lesson here.
2. To have access to the cabin repository on GitHub desktop, the name of your repo needs to be entered in the top-left corner in the box with placeholder “Filter” and “Clone Repository” should be selected.

<img width="429" alt="clone" src="https://user-images.githubusercontent.com/70852990/104529805-8e157580-55d8-11eb-9b12-b004263a71ce.png">

3. Click “Pull Origin” once the repo is cloned to pull to GitHub desktop the most current version of the learning lab.
4. Open VSCode by clicking the button “Open in Visual Studio Code”. The files in the learning lab will be opened in VS code, and now you can complete the lesson (adding the necessary code). You need to add your code in a new file, so make sure you create a new file under the folder in VSCode. When you are done creating your new file and adding the necessary code, save the file and return to GitHub desktop.
5. The change will be shown. Add a summary and description of your change and then click “Commit to main”. Next, click “Push origin”, to push the change made in VSCode to the website.

<img width="900" alt="steps4desktop" src="https://user-images.githubusercontent.com/70852990/104529850-a6859000-55d8-11eb-9a85-908d18b52421.png">

*Remember, each step and lesson is posted on the repo on github.com. You will commit changes when the lesson instructs you to, and once you click “Push origin” and refresh the GitHub page, the issue will close and you can move on.*
<br><br/>
</details>

</details>
<details>
<summary>:exclamation: Help! I don't know how to use it and I need more information.</summary>
  </br>
  If you want to learn more about <b>what it is</b> and <b>how to use it,</b> try taking <a href='https://lab.github.com/githubtraining/introduction-to-github'>this</a> GitHub Learning Lab Course. After finishing it, you will have a strong understanding of all the features GitHub has to offer.
  <br><br/>
</details>

**One very important rule...**
*Don't* work on your code in the web editor. This is bad practice, and you will regret it later.
<details>
<summary>:question: What should I do instead?</summary>
  </br>
Install <a href='https://desktop.github.com/'>Github Desktop</a> and commit from your local computer. We'll go over code editors next if you don't have one to work on your code locally. You can also use <a href='http://kbroman.org/github_tutorial/pages/first_time.html'>git on your commandline</a>.
<br><br/>
</details>

<details>
  <summary><b>:question: How can I make a branch?</b></summary>
  
  Before you continue, we'd recommend going over the [Intro to GitHub Learning Lab](https://lab.github.com/githubtraining/introduction-to-github) if you're unfamiliar with branches.
  
  On the GitHub web editor, you can follow these steps to create a branch:
  1. Click on "Code" at the top left of this page
  2. Click on the gray button that says "main" or "master"
  3. Type in the name of your new branch, and if it doesn't already exist, you will get an option to create a new branch
  4. Always make sure that you are in the correct branching before making any edits
</details>

**Pull Request Guidelines**
* Name the Pull Request `Adding self introduction`
* In the description, place a sentence describing what the Pull Request contributes to the main branch.

Key functions you should be familiar with after this task include:
- Committing changes
- Forking a repository
- Making a new branch
- Making a pull request

**Comment by shreythecray** [comment]
https://changaco.oy.lc/unicode-progress-bars/

**Comment by lazyplatypus** [comment]
this should lead to a PR with a template no?
